### PR TITLE
Release of 0.5.0

### PR DESCRIPTION
**Pull request by njusu**
Release of greykite 0.5.0!

### CODE REVIEW

**Review by al-bert — COMMENTED** [review]
Could you update `AUTHORS.rst` and `HISTORY.rst` as well? (separate commit is fine)

**Comment by njusu** [comment]
> Could you update `AUTHORS.rst` and `HISTORY.rst` as well? (separate commit is fine)

@al-bert Sure, I updated them. The hyperlinks to doc will not work thus I removed them. After the release is published, we could add the links pointing to the updated doc if needed.

**Review by al-bert — APPROVED** [review]
LGTM!

**Review by KaixuYang — APPROVED** [review]
LGTM!

**Review by Reza1317 — APPROVED** [review]
LGTM. I did not spot any issues. Obviously this is a lot to look at and result of many internal reviews. But please have at least two more people review this including Albert Chen.

**Pull request merged**
